### ISSUE TITLE
Config Confusion

### ISSUE THREAD

**Issue by reggi** [microsoftgraph/nodejs-connect-rest-sample#67]
Within the [Configure and run the app](https://github.com/microsoftgraph/nodejs-connect-rest-sample/blob/last_v1_auth/README.md#configure-and-run-the-app) portion of the README.md there's a file mentioned `authHelper.js` which isn't found anywhere in the app.

I've managed to find the config file I believe to be referenced. Except there's two!

* `master/starter-project/utils/config.js`
* `master/utils/config.js`

Also something that needs to be clarified is that `client` and `application` are indeed the same? Because the Azure Dashboard says `ApplicationID` and `ApplicationSecret` and this example code uses the words `ClientId` and `ClientSecret`.

**Comment by jamescro** [comment]
Thanks for alerting us to this issue. We recently updated the sample significantly, so the Readme instructions do need to be changed. 

And yes, you're correct that the ClientID and ClientSecret are the same as the ApplicationId and ApplicationSecret. That terminology needs to be updated as well.

**Comment by jamescro** [comment]
And you can ignore the config.js file that is in the starter-project directory. That directory is for people who are working through the walkthrough here: https://developer.microsoft.com/en-us/graph/docs/concepts/nodejs

**Comment by reggi** [comment]
@jamescro! Thanks for the quick reply!

Also there's no mention of "Secrets" in the dashboard at all, do you have any insight here?

![diagnose and solve problems - microsoft azure 2017-08-04 12-44-33](https://user-images.githubusercontent.com/296798/28978166-ebe804bc-7912-11e7-803f-4b8dc175d3dc.png)

**Comment by reggi** [comment]
Also! I just clicked the `Manifest` button and found a beautiful export of JSON, this is what we should use to bring in all the config variables!

**Comment by jamescro** [comment]
This sample requires a client/application that's registered in at apps.dev.microsoft.com, not the Azure portal. We've used different terms over time. You'll notice that in the app registration portal we use the terms "Application Secret," "Password," and "Public Key" to refer to the same thing:

![image](https://user-images.githubusercontent.com/6666618/28978277-34e88010-78fa-11e7-9853-5870b0acb183.png)

**Comment by reggi** [comment]
Ok Thanks for the clarification @jamescro, but I'm afraid I'm more confused now. 😅 

I was on this page:

https://developer.microsoft.com/en-us/graph/docs/authorization/auth_overview

And if you scroll down for Node.js there's two different URLS. 

* [Azure AD endpoint](https://github.com/microsoftgraph/nodejs-connect-rest-sample/tree/last_v1_auth)
* [Azure AD v2.0 endpoint](https://github.com/microsoftgraph/nodejs-connect-rest-sample)

I didn't realize when I went down this rabbit hole that both were the same repo and different branches. What's the status of these differences? Are both still being pursued? What's the source of truth? Because the [Azure AD v2.0 endpoint README.md](https://github.com/microsoftgraph/nodejs-connect-rest-sample/tree/last_v1_auth#register-the-app) points the the Azure portal.

**Comment by reggi** [comment]
I've signed into [https://apps.dev.microsoft.com](https://apps.dev.microsoft.com) and it makes a bunch more sense now.

**Comment by jamescro** [comment]
The "Deciding between the Azure AD and Azure AD v2.0 endpoints" section of the topic you mentioned explains the differences between the two Azure AD endpoints. They are both supported, but they do have significant differences. (For example, the v1.0 endpoint currently supports conditional access, and the v2 endpoint currently does not.) The v2 endpoint allows you to authenticate all kinds of Microsoft accounts. The v1 endpoint allows you to authenticate only work or school accounts.

The Azure AD endpoint link for node.js links to the "last_v1_auth" branch of this repo, which uses the v1 endpoint. So if you clone that branch of the repo, you'll register your app at the Azure portal. That's why the last_v1_auth Readme links you to the Azure portal (https://github.com/microsoftgraph/nodejs-connect-rest-sample/tree/last_v1_auth#register-the-app). 

The Azure AD v2.0 endpoint link takes you to the default (master) branch of this repo, which uses the v2 endpoint and links you to the app registration portal.

**Comment by reggi** [comment]
Thanks again @jamescro  for the general overview, but the `last_v1_auth` doesn't seem very useful if the Azure Portal is unable to create or generate the client secret. Which is the major point of my confusion.

**Comment by jamescro** [comment]
Sorry. The Azure portal used to use the term "Secret," but now it is using the term "Key," so you can use the "Key" feature that you highlighted in your screen shot earlier in this thread.
I do recommend using the v2 endpoint, though, unless you have special requirements that limit you to v1 only. V2 is generally easier to work with, and it supports live.com and hotmail.com accounts.
