### ISSUE TITLE
API has been updated and is not in Beta anymore

### ISSUE THREAD

**Issue by andrewklaassen** [microsoftgraph/nodejs-connect-rest-sample#70]
API has been updated and is not in Beta anymore so the endpoints have changed.
I.e. https://graph.microsoft.com/beta/me is now https://graph.microsoft.com/v1.0/me

**Comment by jamescro** [comment]
Thanks for the feedback. We're using the /beta endpoint at this point because in this sample we want to use a capability that is still available only on beta: the ability to fetch user profile photos from non-work and non-school Microsoft accounts (live.com). Everything else that this sample does should work on the v1.0 endpoint, though.
